### PR TITLE
Feature/pagination

### PR DESCRIPTION
**Pull request by aabounegm**
Any suggestions about what can be turned into a variable?

### CODE REVIEW

**Comment by aabounegm** [comment]
I'm also thinking there should be a prop that controls whether it should be hidden if only one page exists, but I'm not sure how to name it

**Comment by illright** [comment]
How about `showOnlyPage`?

**Comment by aabounegm** [comment]
Sounds a bit weird. It sort of suggests that there are other things to show, but we only want to show "the page")

**Comment by illright** [comment]
Sounds a little overly poetic for a prop name, but works too

**Pull request merged**
